services:
  php:
    image: php:8.3-fpm
    container_name: app
    working_dir: /phpconf2024
    volumes:
      - "./:/phpconf2024"
    ports:
      - "8000:8000"
    command: php artisan serve --host 0.0.0.0 --port 8000
    env_file:
      - .env
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
